### PR TITLE
!dice to !roll

### PR DESCRIPTION
**Pull request by j2l**
Noticed that !dice didn't work in tests but !roll did 😄

### CODE REVIEW

**Comment by jakethedev** [comment]
Yo, thanks so much, I didn't notice that had broken :sweat_smile:

This is an excellent case for breaking those out into proper mocha tests (#73), hopefully I can get to it soon haha

**Comment by j2l** [comment]
You're welcome!
Did you use some tool to craft the json files?

**Comment by jakethedev** [comment]
I'm very zombie today so I'm not sure which json files: If you mean the test data, no, I hand wrote a few and the rest are copy-pasta haha. If you mean the files under dungeonary, those were all pulled from an open source project that documented the 5e SRD - I think I have a link somewhere in there but I'm not sure

**Comment by j2l** [comment]
Ok, thanks.
Take care if you're not in good shape.
I wrote an issue about some commands.

**Comment by jakethedev** [comment]
Thanks, just sorely lacking some sleep is all haha

**Pull request merged**
